"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-am#7mwoxw6(k_v6=p#@6j#910y+i%@f&*i^+ox^o&+ec&ey!_9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Other apps
    'accounts',
    # Third-party apps for OTP and two-factor authentication
    'corsheaders',#cors
    'axes',#axes for brute force protection
    'django_otp',
    'django_otp.plugins.otp_totp',  # Plugin for time-based one-time passwords
    'django_otp.plugins.otp_static',  # Plugin for static OTP tokens
    # 'django_otp.plugins.otp_email',  # Plugin to send OTP codes via email
    'two_factor',  # App to handle two-factor authentication workflows
]
# Django extensions for development
INSTALLED_APPS += ['django_extensions']

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',#Cores
    # Default middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Middleware for OTP
    'django_otp.middleware.OTPMiddleware',
    # Middleware to manage two-factor authentication processes
    'two_factor.middleware.threadlocals.ThreadLocals',
    # Middleware for brute force protection
    'axes.middleware.AxesMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = False   # ['https://yourdomain.com'] # production
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",  # React local
#     "https://tudominio.com",  # Deploy production
# ]
CORS_ALLOWED_ORIGINS = ["https://localhost:3000"]
CORS_ALLOW_CREDENTIALS = True


# CSRF settings
CSRF_TRUSTED_ORIGINS = [    "https://localhost:3000",]
CSRF_COOKIE_SECURE = True

# Secure ssl direct access
SECURE_SSL_REDIRECT = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Para producción, cambiar a PostgreSQL
        # 'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'creze_db',
        # 'USER': 'creze_user',
        # 'PASSWORD': 'Creze.123.Proyect$',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
        # 'CONN_MAX_AGE': 600,  # Mantiene conexiones por 10 minutos para pooling simple

    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'middlewares.password_validation.CustomPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

LOGIN_URL = '/auth/login/'

# Limit to 10 failures, 1 hour lockout
AXES_FAILURE_LIMIT = 10
AXES_COOLOFF_TIME = 3600  # seconds
# AXES_LOCKOUT_CALLABLE = 'axes.handlers.lockout.get_lockout_response'
AXES_COOLOFF_MESSAGE = "Too many failed logins."

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# CSRF & cookies
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True